__title__ = "inputimeout"
__description__ = "Multi platform standard input with timeout"
__url__ = "https://github.com/johejo/inutimeout"
__version__ = "1.0.5"
__author__ = "Mitsuo Heijo"
__author_email__ = "mitsuo.heijo@gmail.com"
__license__ = "MIT"
__copyright__ = "Copyright 2020 Mitsuo Heijo"
